from __future__ import annotations

import json
import os
import queue
import sys
import tempfile
from pathlib import Path

# Ensure repo root is on sys.path when running backend/server.py directly.
ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from flask import Flask, Response, jsonify, render_template, request, stream_with_context
from backend.dizi_logging.logger import EventLogger
from backend.dizi_logging.profiler import Profiler
from backend.fake_chip.hardware_interface import FakeChipInterface
from models.model_manager import ModelManager
from backend.orchestrator.orchestrator import Orchestrator

app = Flask(
    __name__,
    template_folder=str(ROOT_DIR / "frontend" / "templates"),
    static_folder=str(ROOT_DIR / "frontend" / "static"),
    static_url_path="/static",
)
app.config["MAX_CONTENT_LENGTH"] = 50 * 1024 * 1024  # 50MB file limit

model_manager = ModelManager()
logger = EventLogger()
profiler = Profiler()
fake_hardware = FakeChipInterface()

recent_runs: list[dict] = []


def _as_bool(value, default: bool = True) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def _pipeline_payload(final_output, image_url=None, profile=None) -> dict:
    if final_output is None:
        final_output = "No output generated by agents."

    final_output = str(final_output).strip()
    if not final_output:
        final_output = "No output generated by agents."

    if image_url is not None:
        image_url = str(image_url).strip() or None

    if not isinstance(profile, dict):
        profile = {}

    return {
        "output": final_output,
        "image_url": image_url,
        "profile": profile,
    }


@app.route("/api/stream")
def stream_events():
    def event_generator():
        q: queue.Queue = queue.Queue(maxsize=100)

        def publish(event: dict) -> None:
            try:
                q.put_nowait(event)
            except queue.Full:
                pass

        logger.subscribe(publish)
        try:
            while True:
                try:
                    event = q.get(timeout=15)
                    yield f"data: {json.dumps(event)}\n\n"
                except queue.Empty:
                    yield ": heartbeat\n\n"
        except GeneratorExit:
            return
        finally:
            logger.unsubscribe(publish)

    return Response(stream_with_context(event_generator()), mimetype="text/event-stream")

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/api/health")
def health():
    return jsonify({"status": "healthy", "components": ["backend", "frontend", "orchestrator", "model_manager"]})

@app.route("/api/models", methods=["GET"])
def get_models():
    return jsonify({"models": model_manager.list_models()})

@app.route("/api/switch-model", methods=["POST"])
def switch_model():
    data = request.get_json() or {}
    model_key = data.get("model_key")
    if not model_key:
        return jsonify({"error": "model_key is required"}), 400

    if model_key not in model_manager.list_models():
        return jsonify({"error": f"Model not found: {model_key}"}), 404

    return jsonify({"success": True, "active_model": model_key})

@app.route("/api/run-multi-agent", methods=["POST"])
def run_multi_agent():
    """Execute orchestrator with prompt or uploaded file content."""
    json_data = request.get_json(silent=True) or {}
    allowed_run_modes = {"pipeline", "chat", "code", "image"}
    raw_mode = json_data.get("mode", "pipeline") if request.is_json else request.form.get("mode", "pipeline")
    run_mode = str(raw_mode or "pipeline").strip().lower()
    if not request.is_json and run_mode in {"prompt", "file"}:
        input_mode_value = run_mode
        run_mode = "pipeline"
    else:
        input_mode_value = (
            json_data.get("input_mode", "prompt")
            if request.is_json
            else request.form.get("input_mode", "prompt")
        )

    if run_mode not in allowed_run_modes:
        return jsonify(_pipeline_payload("Invalid mode. Use pipeline, chat, code, or image.")), 400

    extra = json_data.get("extra") if request.is_json else request.form.get("extra")
    use_fake = _as_bool(
        json_data.get("use_fake_hardware") if request.is_json else request.form.get("use_fake_hardware"),
        default=True,
    )
    input_mode = str(input_mode_value or "prompt").strip().lower()

    if input_mode not in {"prompt", "file"}:
        return jsonify(_pipeline_payload("Invalid input_mode. Use 'prompt' or 'file'.")), 400

    temp_path = None
    try:
        prompt_value = json_data.get("prompt") if request.is_json else request.form.get("prompt", "")
        prompt_text = str(prompt_value or "").strip()
        if not prompt_text:
            return jsonify(_pipeline_payload("Prompt requires non-empty text.")), 400

        if run_mode == "pipeline":
            if input_mode == "prompt":
                with tempfile.NamedTemporaryFile(mode="w+", delete=False, suffix=".txt", encoding="utf-8") as tmp:
                    tmp.write(prompt_text)
                    tmp.flush()
                    temp_path = tmp.name
            else:
                file = request.files.get("file")
                if file is None or file.filename == "":
                    return jsonify(_pipeline_payload("File mode requires an uploaded .txt file.")), 400

                content = file.read().decode("utf-8", errors="replace")
                with tempfile.NamedTemporaryFile(mode="w+", delete=False, suffix=".txt", encoding="utf-8") as tmp:
                    tmp.write(content)
                    tmp.flush()
                    temp_path = tmp.name

            if not temp_path or not os.path.exists(temp_path):
                return jsonify(_pipeline_payload("Failed to prepare input for processing.")), 500

        orchestrator = Orchestrator(
            model_manager=model_manager,
            logger=logger,
            profiler=profiler,
            fake_hardware=fake_hardware
        )
        if run_mode == "pipeline":
            final_output, image_url, profile = orchestrator.run(
                temp_path,
                use_fake_hardware=use_fake,
                mode="pipeline",
                prompt=prompt_text,
                extra=extra,
            )
        else:
            final_output, image_url, profile = orchestrator.run(
                prompt_text,
                use_fake_hardware=use_fake,
                mode=run_mode,
                prompt=prompt_text,
                extra=extra,
            )
        print("FINAL OUTPUT:", final_output)
        response_payload = _pipeline_payload(final_output, image_url, profile)

        recent_runs.append({
            "filepath": temp_path or "",
            "use_fake_hardware": use_fake,
            "mode": run_mode,
            "result": response_payload,
            "kv_cache": orchestrator.context_manager.kv_cache,
            "timestamp": len(recent_runs)
        })
        if len(recent_runs) > 20:
            recent_runs.pop(0)

        return jsonify({
            "output": response_payload["output"],
            "image_url": response_payload["image_url"],
            "profile": response_payload["profile"],
        })
    except Exception as e:
        return jsonify(_pipeline_payload(f"Pipeline error: {e}")), 500
    finally:
        if temp_path and os.path.exists(temp_path):
            try:
                os.unlink(temp_path)
            except OSError:
                pass

@app.route("/api/logs", methods=["GET"])
def get_logs():
    return jsonify({"logs": logger.get_events()})

@app.route("/api/profile", methods=["GET"])
def get_profile():
    return jsonify({"profile": profiler.summary()})

@app.route("/api/kv-cache", methods=["GET"])
def get_kv_cache():
    if recent_runs:
        kv_cache = recent_runs[-1].get("kv_cache", {})
        if hasattr(kv_cache, "__dict__"):
            kv_cache = kv_cache.__dict__
        return jsonify({"kv_cache": kv_cache})
    return jsonify({"kv_cache": {}})

@app.route("/api/recent-runs", methods=["GET"])
def recent_runs_api():
    # Return summaries only (not full results to reduce payload)
    summaries = [
        {
            "timestamp": r["timestamp"],
            "filepath": r["filepath"],
            "use_fake_hardware": r["use_fake_hardware"],
            "has_results": "result" in r
        }
        for r in recent_runs
    ]
    return jsonify({"runs": summaries})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5001, debug=True)
