from __future__ import annotations

import time
from dataclasses import asdict
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

from agents import BaseAgent, CheckerAgent, CodeAgent, ConversationAgent, ImageGenAgent, ReaderAgent, SummarizerAgent
from .context_manager import ContextManager
from .router import Router
from .scheduler import Scheduler
from .task import Task
from backend.fake_chip.hardware_interface import FakeChipInterface
from backend.dizi_logging.logger import EventLogger
from backend.dizi_logging.profiler import Profiler
from models.model_manager import ModelManager


class Orchestrator:
    """Coordinates tasks, agents, logging, and profiling."""

    def __init__(
        self,
        agent_classes: Optional[List[type[BaseAgent]]] = None,
        model_manager: Optional[ModelManager] = None,
        logger: Optional[EventLogger] = None,
        profiler: Optional[Profiler] = None,
        router: Optional[Router] = None,
        scheduler: Optional[Scheduler] = None,
        context_manager: Optional[ContextManager] = None,
        fake_hardware: Optional[FakeChipInterface] = None,
    ) -> None:
        self.agent_classes = agent_classes or [
            ReaderAgent,
            SummarizerAgent,
            CheckerAgent,
            ConversationAgent,
            CodeAgent,
            ImageGenAgent,
        ]
        self.model_manager = model_manager or ModelManager()
        self.logger = logger or EventLogger()
        self.profiler = profiler or Profiler()
        self.router = router or Router(self.agent_classes)
        self.scheduler = scheduler or Scheduler()
        self.context_manager = context_manager or ContextManager()
        self.fake_hardware = fake_hardware or FakeChipInterface()

    def _build_pipeline(self, filepath: str, text: Optional[str] = None) -> List[Task]:
        return [
            Task(task_id="task_read", task_type="read", payload={"filepath": filepath, "text": text or ""}),
            Task(task_id="task_summarize", task_type="summarize", payload={}),
            Task(task_id="task_check", task_type="check", payload={}),
        ]

    def _reset_run_state(self, use_fake_hardware: bool) -> None:
        self.use_fake_hardware = use_fake_hardware
        self.scheduler = Scheduler()
        self.context_manager = ContextManager()
        self.logger.reset()
        self.profiler.reset()

    def _execute_task(self, task: Task) -> None:
        agent_name = self.router.route(task.task_type, self.context_manager.state)
        task.assigned_agent = agent_name
        agent_class = self.router.get_agent_class(agent_name)
        if agent_class is None:
            self.logger.log(
                {
                    "event": "agent_not_found",
                    "task_id": task.task_id,
                    "task_type": task.task_type,
                    "agent_name": agent_name,
                }
            )
            task.result = {"error": f"Unknown agent: {agent_name}"}
            return

        agent = agent_class(logger=self.logger.log, model_manager=self.model_manager)
        self.logger.log({"event": "task_start", "task_id": task.task_id, "agent": agent_name})
        start_time = time.time()

        if task.task_type == "read":
            task.payload["filepath"] = task.payload.get("filepath")

        if task.task_type == "summarize":
            reader_output = self.context_manager.get("text", "")
            summary_result = agent.run(reader_output)
        else:
            task.payload.update(self.context_manager.state)
            task_result = agent.run(task.payload)

        if task.task_type == "summarize":
            if isinstance(summary_result, dict):
                summary = (
                    summary_result.get("text")
                    or summary_result.get("output")
                    or summary_result.get("summary")
                )
            else:
                summary = summary_result

            summary = str(summary or "").strip()
            if not summary:
                summary = "No output generated by agents."
            task_result = {"summary": summary}

        duration = time.time() - start_time
        self.profiler.record_task(
            task_id=task.task_id,
            agent=agent_name,
            task_type=task.task_type,
            duration_seconds=duration,
            token_count=self._estimate_tokens(task_result),
        )

        self.logger.log(
            {
                "event": "task_complete",
                "task_id": task.task_id,
                "agent": agent_name,
                "task_type": task.task_type,
                "duration": duration,
                "result_keys": list(task_result.keys()) if isinstance(task_result, dict) else [],
            }
        )

        task.result = task_result
        if isinstance(task_result, dict):
            self.context_manager.update(task_result)
            if task.task_type == "summarize":
                self.context_manager.record_kv_write(count=1)
            if task.task_type == "check":
                self.context_manager.record_kv_read(hit=True)
            self.logger.log(
                {
                    "event": "kv_cache_update",
                    "task_id": task.task_id,
                    "kv_cache": asdict(self.context_manager.kv_cache),
                }
            )

        self.logger.log({
            "event": "profile_update",
            "task_id": task.task_id,
            "profile": self.profiler.summary(),
        })

        if self.use_fake_hardware and task.task_type in ("summarize", "check"):
            profile = self.fake_hardware.execute_attention(seq_len=32, head_dim=64, num_heads=8, precision="int8")
            self.logger.log(
                {
                    "event": "hardware_profile",
                    "task_id": task.task_id,
                    "agent": agent_name,
                    "profile": profile.__dict__,
                }
            )

    @staticmethod
    def _estimate_tokens(result: Any) -> int:
        if isinstance(result, str):
            return len(result.split())
        if not isinstance(result, dict):
            return 0
        text = result.get("summary") or result.get("checked_summary") or result.get("output") or result.get("text") or ""
        return len(text.split())

    def _run_single_agent_mode(
        self,
        mode: str,
        prompt: str,
        extra: Any = None,
        use_fake_hardware: bool = True,
    ) -> tuple[str, Optional[str], Dict[str, Any]]:
        self._reset_run_state(use_fake_hardware)
        mode_agent_map = {
            "chat": ConversationAgent,
            "code": CodeAgent,
            "image": ImageGenAgent,
        }
        agent_class = mode_agent_map[mode]
        agent = agent_class(logger=self.logger.log, model_manager=self.model_manager)
        task_id = f"task_{mode}"
        self.logger.log({"event": "task_start", "task_id": task_id, "agent": agent_class.__name__})
        start_time = time.time()

        result = agent.run({"prompt": prompt, "extra": extra})
        duration = time.time() - start_time
        self.profiler.record_task(
            task_id=task_id,
            agent=agent_class.__name__,
            task_type=mode,
            duration_seconds=duration,
            token_count=self._estimate_tokens(result),
        )

        if isinstance(result, dict):
            self.context_manager.update(result)
            final_output = result.get("output") or result.get("text") or ""
            image_url = result.get("image_url") or None
            result_keys = list(result.keys())
        else:
            final_output = result
            image_url = None
            result_keys = []

        final_output = str(final_output or "").strip()
        if not final_output:
            final_output = "No output generated by agents."

        self.logger.log(
            {
                "event": "task_complete",
                "task_id": task_id,
                "agent": agent_class.__name__,
                "task_type": mode,
                "duration": duration,
                "result_keys": result_keys,
            }
        )
        self.logger.log(
            {
                "event": "profile_update",
                "task_id": task_id,
                "profile": self.profiler.summary(),
            }
        )

        return final_output, image_url, self.profiler.summary() or {}

    def run(
        self,
        filepath: str,
        use_fake_hardware: bool = True,
        mode: str = "pipeline",
        prompt: Optional[str] = None,
        extra: Any = None,
    ) -> tuple[str, Optional[str], Dict[str, Any]]:
        mode = str(mode or "pipeline").strip().lower()
        if mode in {"chat", "code", "image"}:
            return self._run_single_agent_mode(
                mode=mode,
                prompt=str(prompt if prompt is not None else filepath),
                extra=extra,
                use_fake_hardware=use_fake_hardware,
            )
        if mode != "pipeline":
            raise ValueError("Invalid orchestrator mode. Use pipeline, chat, code, or image.")

        self._reset_run_state(use_fake_hardware)

        source_text = prompt
        if source_text is None and filepath and not Path(str(filepath)).exists():
            source_text = str(filepath)

        tasks = self._build_pipeline(filepath, source_text)
        self.scheduler.extend(tasks)

        while self.scheduler.has_work():
            task = self.scheduler.next_task()
            if task is None:
                break
            self._execute_task(task)

        summary = str(self.context_manager.get("summary") or "").strip()
        if not summary:
            summary = "No output generated by agents."
        final_output = summary

        image_url = self.context_manager.get("image_url") or None
        profile = self.profiler.summary() or {}

        return final_output, image_url, profile
