from __future__ import annotations

from datetime import datetime
from typing import Any, Dict

from .base_agent import BaseAgent


class CheckerAgent(BaseAgent):
    """Checks and refines text produced by earlier agents.

    This agent exists to show how a second inference step can be chained.
    In real Phase 1 usage it can also apply simple grammar checks or style fixes.
    """

    def _clean_text(self, text: str) -> str:
        cleaned = " ".join(text.split())
        if cleaned and cleaned[-1] not in ".!?":
            cleaned += "."
        return cleaned

    def run(self, context: Dict[str, Any]) -> Dict[str, Any]:
        summary = str(context.get("summary") or "").strip()
        self._log("start", {"summary_length": len(summary)})

        if not summary:
            checked = "No summary available to check."
            self._log("fallback", {"checked_summary": checked})
            return {"checked_summary": checked, "checked_at": datetime.utcnow().isoformat()}

        checked = self._clean_text(summary)
        if not checked:
            checked = "No output generated by agents."
        self._log("success", {"checked_length": len(checked)})
        return {"checked_summary": checked, "checked_at": datetime.utcnow().isoformat()}
