from __future__ import annotations

import re
from typing import Any

from .base_agent import BaseAgent


class _SummarizerModelAdapter:
    def __init__(self, model_manager: Any = None) -> None:
        self.model_manager = model_manager

    def generate(self, prompt: str) -> str:
        if self.model_manager is None or not hasattr(self.model_manager, "generate"):
            return ""
        return self.model_manager.generate("llama3", prompt, max_tokens=128)


class SummarizerAgent(BaseAgent):
    """Summarizes text from the shared context.

    In Phase 1 this agent uses a simple rule-based fallback when no
    local model is available. That keeps the architecture usable even
    without heavy model dependencies.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.model = _SummarizerModelAdapter(self.model_manager)

    _STOPWORDS = {
        "about", "after", "again", "also", "because", "before", "being", "could",
        "does", "doing", "down", "from", "have", "into", "just", "like", "more",
        "most", "only", "over", "please", "should", "some", "such", "that",
        "their", "there", "these", "they", "this", "through", "what", "when",
        "where", "which", "while", "with", "would", "your",
    }

    @staticmethod
    def _strip_summary_instruction(text: str) -> str:
        patterns = [
            r"^\s*(please\s+)?summari[sz]e\s+(the following|this|that)?\s*[:\-]?\s*",
            r"^\s*(can|could)\s+you\s+summari[sz]e\s+(the following|this|that)?\s*[:\-]?\s*",
            r"^\s*(give|write)\s+me\s+a\s+summary\s+of\s+(the following|this|that)?\s*[:\-]?\s*",
            r"^\s*(tl;?dr|tldr)\s*[:\-]?\s*",
        ]
        cleaned = text
        for pattern in patterns:
            cleaned = re.sub(pattern, "", cleaned, flags=re.IGNORECASE)
        return cleaned.strip() or text.strip()

    def _keyword_phrase(self, text: str, max_words: int = 8) -> str:
        words = re.findall(r"[A-Za-z][A-Za-z0-9_-]*", text)
        keywords = []
        for word in words:
            lowered = word.lower()
            if len(lowered) < 4 or lowered in self._STOPWORDS:
                continue
            if lowered not in [item.lower() for item in keywords]:
                keywords.append(word)
            if len(keywords) >= max_words:
                break
        return ", ".join(keywords)

    @staticmethod
    def _split_sentences(text: str) -> list[str]:
        parts = re.split(r"(?<=[.!?])\s+", text)
        return [part.strip() for part in parts if part.strip()]

    def _fallback_summarize(self, text: str) -> str:
        clean_text = self._strip_summary_instruction(" ".join(text.split()))
        sentences = self._split_sentences(clean_text)
        if not sentences:
            return "No output generated by agents."

        keywords = self._keyword_phrase(clean_text)
        words = clean_text.split()
        if len(sentences) <= 2 and len(words) <= 36:
            if keywords:
                return f"Summary: The text focuses on {keywords}."
            return "Summary: The text is brief and direct."

        selected = sentences[:2]
        summary = " ".join(selected)
        if len(summary.split()) > 42:
            summary = " ".join(summary.split()[:42]).rstrip(".,;:") + "."

        if self._matches_input(summary, clean_text):
            if keywords:
                return f"Summary: The text focuses on {keywords}."
            summary = " ".join(words[:24]).rstrip(".,;:") + "."

        if not summary.lower().startswith("summary:"):
            summary = f"Summary: {summary}"
        return summary

    @staticmethod
    def _matches_input(summary: str, text: str) -> bool:
        normalized_summary = summary.strip().rstrip(".!?").strip()
        normalized_text = text.strip().rstrip(".!?").strip()
        return normalized_summary == normalized_text

    def run(self, text):
        if isinstance(text, dict):
            text = text.get("text") or text.get("input") or ""
        text = str(text or "").strip()
        self._log("start", {"input_length": len(text)})

        if not text:
            summary = "No text available to summarize."
            self._log("fallback", {"summary": summary})
            return summary

        prompt = f"Summarize the following text:\n\n{text}"
        try:
            summary = self.model.generate(prompt)
        except Exception as exc:
            self._log("generation_failed", {"error": str(exc)})
            summary = ""

        summary = str(summary or "").strip()
        if not summary or self._matches_input(summary, text) or self._matches_input(summary, prompt):
            summary = self._fallback_summarize(text)

        if not summary:
            summary = "No output generated by agents."

        self._log("success", {"summary_length": len(summary)})
        return summary
